baseURL = 'https://cashflow-workbook.com/'
languageCode = 'en-us'
title = 'Cashflow & Networth Analysis Workbook'
theme = 'bigspring-light'
summaryLength = 10

[pagination]
  pagerSize = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
