author = "Sean Jackman"
description = "Take control of your personal finances with a powerful Excel workbook featuring spending analysis, networth tracking, and financial independence planning."
logo = "images/logo.png"
favicon = "images/favicon.png"
logo_width = "180px"
logo_webp = true
theme_switcher = false
mainSections = ["blog"]

# Color and font variables required by SCSS
[variables]
color_primary = "#0AA8A7"
color_secondary = "#376f92"
body_color = "#fff"
text_color = "#777"
text_dark = "#222"
text_light = "#959595"
border_color = "#ECECEC"
dark_body_color = "#1E262C"
dark_text_color = "#cbcbcb"
dark_text_light = "#959595"
dark_text_dark = "#fff"
dark_border_color = "#4e4e4e"
black = "#101418"
white = "#fff"
light = "#EDF6F5"
dark = "#1b2229"

# Font variables
font_size = "16px"
font_scale = "1.25"
font_primary = "Lato:wght@300;400;500;600;700"
font_primary_type = "sans-serif"
font_icon = "Font Awesome 6 Free"
